development:
  adapter: postgresql
  database: dhanak_dev
  host: localhost
  timeout: 5000
  username: prakhar
  password: amsterdam

test:
  adapter: postgresql
  database: dhanak_test
  host: localhost
  timeout: 5000
  username: prakhar
  password: amsterdam

production:
  adapter: postgresql
  database: dhanak
  host: localhost
  timeout: 5000
