development:
  adapter: postgresql
  database: dhanak_dev
  host: localhost
  timeout: 5000
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: dhanak_test
  host: localhost
  timeout: 5000
  username: postgres
  password: password

production:
  adapter: postgresql
  database: dhanak
  host: localhost
  timeout: 5000
