# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfc9202f849b3294fa602b8c304f78bae61a9a3881006490635601df08b12f6fe6b4a04b13a9ac817583c509fbd65d40e2d42c676cd82235e2abcf837132eb50

test:
  secret_key_base: 21b3568cf9cb2623facbc5527690c4de0dfe9c63de4363780d9e7402eb36dc5bee0f152a0371e8ac5af034c4c6ec0f631bfc2a27611352a23a1852b500191f95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
